# -*- coding: utf-8 -*-
"""Python_ToDo_List

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lEluoUq-FOW79qDWcMYHHuYOqq-BF10n
"""

tasks = []

while True:
    print("\n--- TO-DO LIST ---")
    print("1. Add Task")
    print("2. View Tasks")
    print("3. Remove Task")
    print("4. Exit")

    choice = input("Enter your choice: ")

    if choice == "1":
        task = input("Enter the task: ")
        tasks.append(task)
        print("Task added!")
    elif choice == "2":
        print("\nYour Tasks:")
        for i, t in enumerate(tasks, 1):
            print(f"{i}. {t}")
    elif choice == "3":
        remove = int(input("Enter task number to remove: "))
        if 1 <= remove <= len(tasks):
            removed_task = tasks.pop(remove - 1)
            print(f"Removed: {removed_task}")
        else:
            print("Invalid number!")
    elif choice == "4":
        print("Exiting To-Do List. Bye!")
        break
    else:
        print("Invalid choice!")